### ISSUE TITLE
Publish a realease

### ISSUE THREAD

**Issue by brunetton** [domportera/Reaper-LAN-OSC-MIDI-Faders-Android#2]
Hi ! Thank you for doing open source :)

I'd like to test your project; but I can't compile the APK by myself (I'm not an Android dev for now). 
Could you please publish a [Release](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) ? 

It would be even better to publish it to F-droid when you feel it a minimum ready to use !

Thanks a lot

**Comment by domportera** [comment]
hey glad you're interested! there's still quite some work to do before the latest updates are release-ready. 2D faders don't work on Android, a handful of features have yet to be implemented, and it's overall just untested. But I'd love if you're willing to test it out once I feel like it's at a minimum beta-test state. 

You can get the old version [here](https://forum.cockos.com/showthread.php?t=235365) in the meantime
I do plan on publishing to F-Droid and Google Play once I have a pretty bullet-proof build though!

**Comment by domportera** [comment]
And by the way anyone can compile an APK themselves in Unity. super easy - just download the correct editor version (v 2021.2.3 at the time of latest commit) and make sure to install the Android SDK/JDK along with it (it's an installer option).

**Comment by colonel-blimp** [comment]
> there's still quite some work to do before the latest updates are release-ready

Long-time fan of this project, but in a similar boat as @brunetton―would you consider publishing a release + APK with  the "`This is a pre-release`" checkbox  checked? 

Pre-releases are labeled as not production-ready and aren't visible from the repo's main page―they only show up up if you visit the /releases page directly.

**Comment by domportera** [comment]
Wow! I figured everyone long forgot this project even existed.

Since there is a demand, I can whip up a build shortly. But if I remember correctly its current progress in development is very incomplete. I have a long to-do list on it that involves a bunch of bugs and potential refactors for extended functionality, but if y'all are willing to use it and give feedback/bug reports that is definitely appreciated! In that case maybe I'll come back to actually finish the damn thing

And sorry @brunetton for keeping you waiting so long, as you might have guessed I haven't really worked on this project since. I planned on finishing up what i was working on and publishing a release shortly after your comment, but life got in the way. In the meantime, I can make an in-progress build for y'all

**Comment by brunetton** [comment]
> Wow! I figured everyone long forgot this project even existed.
> 
> Since there is a demand, I can whip up a build shortly. But if I remember correctly its current progress in development is very incomplete. I have a long to-do list on it that involves a bunch of bugs and potential refactors for extended functionality, but if y'all are willing to use it and give feedback/bug reports that is definitely appreciated! In that case maybe I'll come back to actually finish the damn thing
> 
> And sorry @brunetton for keeping you waiting so long, as you might have guessed I haven't really worked on this project since. I planned on finishing up what i was working on and publishing a release shortly after your comment, but life got in the way. In the meantime, I can make an in-progress build for y'all

Thanks ! No problem for the delay. And yep a beta release would be great ! And some explanations on how to compile it in the README would be great also, I didn't succeeded using Android Studio.

Thanks again :)

**Comment by domportera** [comment]
you gotta use [Unity](https://unity3d.com/get-unity/download/archive) to compile, so it makes sense you wouldn't have been able to with Android Studio. Fortunately, the build process is very simple. I can update the readme soon!

**Comment by domportera** [comment]
I've published a release @brunetton @colonel-blimp

https://github.com/domportera/Reaper-LAN-OSC-MIDI-Faders-Android/releases/tag/snapshot-12-2-2022

Hope it works well for you in whatever state it's currently in. I know some bugs exist and some features are incomplete. Let me know if you have any issues or feedback!

**Comment by brunetton** [comment]
Thanks ! I'll definitely try it soon
